# Generated by Django 4.2.9 on 2024-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='date_used',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redeem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
