# Generated by Django 5.0.3 on 2024-03-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_background_photo_hover_background_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='photo_hover',
            field=models.ImageField(default='backgrounds/default.png', upload_to='backgrounds'),
        ),
    ]
