# Generated by Django 4.2.9 on 2024-03-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0004_alter_background_photo_hover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='frame_id',
        ),
    ]
