# Generated by Django 4.2.9 on 2024-03-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0004_frame_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
