# Generated by Django 4.2.9 on 2024-04-13 14:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0005_alter_frame_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
