# Generated by Django 5.0.3 on 2024-03-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_alter_layout_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='photo_hover',
            field=models.ImageField(default='layouts/default.png', upload_to='layouts'),
        ),
        migrations.AddField(
            model_name='layout',
            name='position',
            field=models.TextField(default='center'),
        ),
    ]
