# Generated by Django 5.0.3 on 2024-03-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_rename_photo_hover_layout_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='background',
            new_name='photo_cover',
        ),
    ]
