# Generated by Django 4.2.9 on 2024-03-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0004_frame_position'),
        ('layout', '0007_rename_photo_hover_layout_photo_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='frame',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frame.frame'),
        ),
    ]
