# Generated by Django 4.2.9 on 2024-03-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0011_alter_layout_frame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='background_id',
            new_name='background',
        ),
    ]
